config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/index'

  get 'users/show'

  get 'users/new'

  get 'users/edit'

        root to: 'blogs#index'

        # Add prefixes to routes using `as: "some_prefix"` syntax
        get '/blogs', to: 'blogs#index', as: "blogs"

        get '/blogs/new', to: 'blogs#new', as: "new_blog"

        get '/blogs/:id', to: 'blogs#show', as: "blog"

        get '/blogs/:id/edit', to: 'blogs#edit', as: "edit_blog"        

        post "/blogs", to: "blogs#create"

        # The update route
        patch "/blogs/:id", to: "blogs#update"

        # the destroy route
        delete "/blogs/:id", to: "blogs#destroy"
 ######login#####
  get "/login", to: "sessions#new"

  post "/sessions", to: "sessions#create"

  get "/sign_up", to: "users#new", as: "sign_up"

  get "/logout", to: "sessions#destroy", as: "logout"

  resources :users
      
    end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title, :content
end

app/models/blog.rb
class Blog < ActiveRecord::Base
def make_request
request = Typhoeus::Request.new(
  "http://access.alchemyapi.com/calls/text/TextGetRankedKeywords",
  method: :get,
  params: { text: content, apikey: keywordExtractMode: "normal" },
  headers: { Accept: "text/html" }
)

request.run

response = request.response
puts response.code
response.total_time
response.headers
response.body

parseResponse = JSON.parse(response)
puts parseResponse

end 


end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
 has_secure_password

  def self.confirm(email_param, password_param)
    user = User.find_by({email: email_param})
    if user
    user.authenticate(password_param)
  else
    false
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :find_uer_article, only: [:destroy, :update, :edit]
  before_filter :logged_in?
  
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.create(article_params)
    redirect_to article_path(@article.id)
  end

  def show
    find_article
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article.id)
  end

  def delete
    @articles.destroy
    redirect_to articles_path
  end


  private
    def find_user_article
      @article = current_user.articles.find_by({id: params[:id]})
      unless @article
        redirect_to user_path(current_user)
      else
        @article
      end
    end
    
    def find_article
      @article = Article.find_by({id: params[:id]})
    end

    def article_params
      params.require(:article).permit(:title, :content)
    end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
    render :index
  end

  def new
    @blog = Blog.new
    render :new
  end

  def create
    new_creature = params.require(:blog).permit(:title, :date, :content)
    blog = Blog.create(new_creature)
    redirect_to blog_path(blog.id)
  end

  def show
    id = params[:id]
    @blog = Blog.find(id)
    render :show
  end

  def edit
    if current_user 
    id = params[:id]
    @blog = Blog.find(id)
    render :edit
  else
    redirect_to login_path
  end
  end

  def update
        
    blog = Blog.find(params[:id])

    # get updated data
    blog_params = params.require(:blog).permit(:title, :date, :content)
    # update the creature
    blog.update(blog_params)

    #redirect to show
    # redirect_to "/creatures/#{creature_id}"
    redirect_to blog_path(blog)
  end 

    def destroy
    id = params[:id]
    blog = Blog.find(id)
    blog.destroy
    redirect_to "/blogs"
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:user)
    user = User.confirm(user_params[:email], user_params[:password])
    if user
      # use our handy login method
      login(user)
      redirect_to user_path(user.id)
    else
       # Flash an error message
      flash[:error] = "Failed To Authenticate. Please try again."
      redirect_to "/login"
    end

  end

  def destroy
    logout
    redirect_to "/blogs"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:show]
  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to user_path(@user.id)
  end

  def edit
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # takes in a user object
  def login(user)
    # stores their id in the session
    session[:user_id] = user.id
    # stores the user in an instance variable
    @current_user = user
  end

   def logout
    # set @current_user and session to nil
    #   this effectively forgets the user
    @current_user = session[:user_id] = nil
  end


  def logged_in?
    if current_user == nil
      redirect_to "/login"
    end
  end

  def current_user
    # finds a logged in user using the session[:user_id]
    @current_user = @current_user || User.find_by(id: session[:user_id])
  end
end

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>
<%= form_for :article, url: '/articles', method: 'post' do |f| %>
  <%= f.text_field  :title, placeholder: 'title' %>
  <%= f.text_area :content, placeholder: 'content' %>
  <%= f.submit 'save article' %>
<% end %>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

<h2>
  <%= @article.title %>
</h2>

<div>
  content
  <p>
    <%= @article.content %>
  </p>
</div>

app/views/blogs/edit.html.erb
<html>
<head>
  <title></title>
</head>
<body>
<div id="editContainer">
<%= form_for @blog do |f| %>
  <div id="editTextField">
    <%= f.text_field :title, placeholder:"title" %>
    <%= f.text_field :date, placeholder:"date" %><br><br>
    <%= f.text_area :content, placeholder:"Your Own Thoughts", :size => "90x30" %><br>
    <%= f.submit "update blog" %>

<% end %>
</div>
</div>
</body>
</html>

app/views/blogs/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<div class="container" id="main-content">
  
<h1>Sea Legs</h1> 
<h3> the illusion of motion after spending time at sea </h3>

<% @blogs.each do |blog| %>

<div class="row">
  <div id= "postLink" class="col-md-1"><%= link_to blog.title, blog_path(blog.id) %></div>    
  <!-- do another each.do |blog| to get hyperlinks to work -->
 <!-- @blogs.each do |blog| %> -->
<div id= "postBlog" class="col-lg-3 col-md-4 col-sm-6 col-xs-12"> 
      <!-- Title: --> <%= blog.title %> <br>
      <!--  date: --> <%=  blog.date %> <br>
      <!-- Content: --> <%= blog.content %>
       <%= button_to "Delete", blog, method: :delete %>
       <%= button_to "Edit", edit_blog_path(blog),method: :get %> 
</div> 

<% end %>
</div>
</div>
<footer>User Resources: <a href="/blogs/new">New Post,</a> <a href="/blogs/:id/edit">Edit,</a> Delete</footer>
<script type="text/javascript" src= "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

</body>
</html>

app/views/blogs/new.html.erb
<html>
<head>
  <title></title>
</head>
<body>
 <div id="newContainer">
  <%= form_for @blog do |f| %>
    <div id="newTextField">
    <%= f.text_field :title, placeholder: "Title" %>
    <%= f.text_field :date, placeholder: "Date" %> <br><br>
    <%= f.text_area :content, placeholder:"Your Own Thoughts", :size => "90x30"%><br>
    <%= f.submit "save blog post" %>

<% end %>
</div>
</div>
</body>
</html>

app/views/blogs/show.html.erb
<div id='singleBlog'>


  Title: <%= @blog.title %> <br>
  Date: <%= @blog.date %> <br>
  Content: <%=  @blog.content %>
</div>

<% if current_user %>
  <%= link_to "edit", edit_blog_path(@blog) %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogAppRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= form_for @user do |f| %>
    <div>
    <%= f.text_field :email %>
    </div>
    <div>
      <%= f.text_field :password %>
    </div>
    <div>
      <%= f.text_field :password_confirmation %>
    </div>
    <div>
      <%= f.submit %>
    </div>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
  Welcome, <%= current_user.email %>!.
  <%= link_to "view all", blogs_path %>
  